### ISSUE TITLE
Return Type of buildUrl function is any

### ISSUE THREAD

**Issue by oeyazgan** [meabed/build-url-ts#14]
I don't know if this is on purpose or not, but I think it would be safer if the return type of `buildUrl` function was `string` instead of `any`, or if the users should expect other types, then other types instead of any, so that we'd know what to expect. It'd be awesome if that's a doable change.

**Comment by meabed** [comment]
Thanks @oeyazgan I have fixed this in the latest release - https://unpkg.com/browse/build-url-ts@6.1.3/dist/build-url.d.ts 
Would you check and let me know if this fix the type issue.
