### ISSUE TITLE
Links on NPM to the Github repository are incorrect

### ISSUE THREAD

**Issue by honungsburk** [meabed/build-url-ts#164]
NPM: `https://github.com/meabed/build-url`
Should be: `https://github.com/meabed/build-url-ts`

npm: https://www.npmjs.com/package/build-url-ts
![Screenshot 2022-10-26 at 08 57 20](https://user-images.githubusercontent.com/21693578/197956257-1ee62b5d-9c9a-4c6f-b698-2f7d40714d00.png)

**Comment by meabed** [comment]
Fixed - thank you
