### ISSUE TITLE
Array query param build incorrect

### ISSUE THREAD

**Issue by cap1024** [meabed/build-url-ts#391]
Description:

- Comma between array values is URL encoded but shouldn't.

Use case:
```
buildUrl({
    path: 'entity/properties',
    queryParams: {
        fields: ['field_1_', 'field_2_'],
    },
});
```
Actual result:
```
'/entity/properties?fields=field_1_%2Cfield_2_'
```
Expected result:
```
'/entity/properties?fields=field_1_,field_2_'
```

**Comment by meabed** [comment]
@cap1024 this is encoded as it is url, if you want it decoded you could decode the whole string in your code

**Comment by cap1024** [comment]
It's example from ReadMe file:

![image](https://github.com/meabed/build-url-ts/assets/5022086/a1c0a43f-8dc2-4324-88dc-204d7ccfc9d1)

It should work without URL encoded commas according to this example.

**Comment by meabed** [comment]
@cap1024 ah, thanks for pointing it out, I will fix it shortly.

**Comment by cap1024** [comment]
Hi @meabed,

Looking at post [how to send an array in url request](https://stackoverflow.com/questions/11889997/how-to-send-an-array-in-url-request) the following suggestion appeared: replace `disableCSV` boolean option with three values enum to cover most popular cases. What do you think about this?

**Comment by meabed** [comment]
Sounds good to me, would you be able to open PR for this.
I would suggest keep both options for backward compatibility.
