### ISSUE TITLE
When the url is undefined and the path parameter is present, the following error is reported

### ISSUE THREAD

**Issue by persiliao** [meabed/build-url-ts#97]
```ts
buildUrl(undefined, {
  path: "/api"
})
```

>  TypeError: Cannot read properties of undefined (reading 'length')

      49 |   lowerCase?: boolean
      50 | ) {
    > 51 |   if (builtUrl[builtUrl.length - 1] === "/") {
         |                         ^
      52 |     builtUrl = builtUrl.slice(0, -1);
      53 |   }

**Comment by meabed** [comment]
fixed #209
